### ISSUE TITLE
Mention that "Allow remote control apps" needs to be active

### ISSUE THREAD

**Issue by dicer** [MarioNoll/WG-Auto-Connect#3]
Just tried your app and it initially didn't work for me, because "Allow remote control apps" was deactivated in the wireguard apps advanced settings. Maybe you could mention this requirement in your app? Just to save people some time searching for this ;)
Also not sure if I disabled this or it was disabled by default, but a hint can't hurt, right?

**Comment by MarioNoll** [comment]
Absolutely, thanks for reaching out! :raised_hands:  I am not sure either if I enabled this and then just forgot about it or if it was enabled by default :smile: In any case I'll add a note :+1:

**Comment by uli42** [comment]
what wireguard app offers advanced settings? Mine is the official one (com.wireguard.android 1.02.20260315; using it on Android 11)) and  only offers to add or delete connections!? There is no advanced settings dialog anywhere.

**Comment by MarioNoll** [comment]
I am using the same version on Android 17

<img width="40%" alt="Image" src="https://github.com/user-attachments/assets/105da5dc-8df4-468b-8430-7fd97ab10289" /><img width="40%" alt="Image" src="https://github.com/user-attachments/assets/1f52a7d1-408b-41b6-86ae-46e86c25dd28" />

**Comment by uli42** [comment]
Thanks for the screenshot. Interesting. How do you enter the settings
screen? I do not seem to have any way to go there.

**Comment by MarioNoll** [comment]
There's a dot menu in the top bar,  that leads to the above settings screen.

<img width="30%" alt="Image" src="https://github.com/user-attachments/assets/e016a0ce-a149-4996-86c4-dc5835eaac75" />

**Comment by uli42** [comment]
Well, then the problem is that there is no top bar on my TV stick (waipu
TV). Wireguard  looks like this:
