### ISSUE TITLE
Min SDK version

### ISSUE THREAD

**Issue by mpeter50** [MarioNoll/WG-Auto-Connect#4]
I have just seen this app mentioned in [this weeks TWIF](https://f-droid.org/en/2024/02/15/twif.html), and I was excited to try it out as I need to manage the VPN connection a lot.

However I have seen that the app has a limitation of only being installable on at least Android 10.

Is there any technical reasons behind this limit, or you just did not have a device to test with, or something else?
If its the second one, would you consider lowering the limit if someone tested it and turned out it works fine?

**Comment by MarioNoll** [comment]
There are some APIs used that are only available in newer versions iirc. What version are you aiming for? I'll check if it is possible to lower the minSdk.

**Comment by mpeter50** [comment]
I'm aiming for SDK 23

**Comment by MarioNoll** [comment]
@mpeter50 I released `1.1.0` with minSdk 23. Would be great if you could give some feedback if everything works, I could only test on sdk 25.

**Comment by mpeter50** [comment]
The update has reached F-droid, and I have just updated it. After toggling wifi a few times the app is working perfectly!
Thank you!

**Comment by MarioNoll** [comment]
Happy to hear that, thx for the feebback :raised_hands:
